import 'tailwindcss/tailwind.css';
import '../app/globals.css'
import Container from "../components/ContainerApp";
import Header from "../components/Header";
import LeftSide from "../components/LeftSide";
import MainContainer from "../components/MainContainer";
import ProfileMain from "../components/ProfileMain";
import Head from 'next/head';

export const metadata = {
  title: 'Air Play',
  description: 'Generated by create next app',
}

export default function ProfilePage(){
  return ( 
    <div className='b-col'>
      <Head>
        <title>Air Play - Profile</title>
      </Head>
        <Container>
          <Header/>
          <MainContainer isGrid={false} >
            <LeftSide/>
            <ProfileMain/>
          </MainContainer>
        </Container>
    </div>
  );
}